############################# English ############################
[en]
languageName = "En"
title = "DoNaSo"
contentDir = "content/english" # content/english
weight = 1
########### footer content ##########
footer_menu_left = "Starup"
footer_menu_middle = "Sản phẩm"
footer_menu_right = "Hỗ trợ"
footer_content = "Startup ứng dụng AI, Big Data, Digital Platform, và IoT, tập trung chuyển đổi số, chuyển đổi xanh với mục tiêu phát triển bền vững và bảo vệ môi trường."
# copyright
copyright = "Thiết kế và Phát triển bởi [DoNaSo](https://donaso.vn)"



############################# Deutsch ############################
[de]
languageName = "De"
title = "Bigspring Hugo"
contentDir = "content/deutsch" # content/german
weight = 2
########### footer content ##########
footer_menu_left = "Firma"
footer_menu_middle = "Produkte"
footer_menu_right = "Support"
footer_content = "Lorem ipsum dolor sit amet, consectetur elit. Consjat tristique eget amet, tempus eu at cttur."
# copyright
copyright = "Design von [Themefisher](https://themefisher.com/) Entwickelt von [Gethugothemes](https://gethugothemes.com/)"